# Generated by Django 3.2.9 on 2021-11-13 16:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('host_name', models.CharField(max_length=50)),
                ('host_session_key', models.TextField()),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_session_key', models.TextField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['host_session_key'], name='board_board_host_se_6f52b0_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['user_session_key'], name='board_membe_user_se_1d8751_idx'),
        ),
    ]
